site_name: pyimg Documentation
repo_name: 'pyimg'
repo_url: https://github.com/grqphical07/pyimg

theme:
  name: material
  logo: assets/pyimg-logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.path

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Open Sans
  favicon: assets/pyimg-logo.png

nav:
  - Home: index.md
  - Usage: usage.md
  - Transform: transform.md
  - Filters: filters.md
  - Operations: operations.md